project_name: controller
debug: false
docker_socket: unix:///var/run/docker.sock
container_frr: frr
container_tester: tester
dut_ssh_host: frr
dut_ssh_port: 22
dut_ssh_username: root
dut_ssh_password: null
dut_ssh_known_hosts: null
dut_command_timeout: 60.0
dut_devices:
- host: 172.20.0.2
  port: 22
  username: root
  password: rootpassword
- host: frr
  port: 22
  username: root
  password: rootpassword
