frr version 8.4.1_git
frr defaults traditional
hostname 5daf56fcfdf1
log stdout
no ipv6 forwarding
!
router bgp 65001
 bgp router-id 1.1.1.1
 neighbor 172.18.0.3 remote-as 65001
 neighbor 172.20.0.3 remote-as 65001
exit
!
